# Generated by Django 2.0.4 on 2018-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
