# Generated by Django 2.0.4 on 2018-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_ongoingprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingprojects',
            name='transaction',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
