# Generated by Django 2.0.4 on 2018-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0004_ongoingprojects_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingprojects',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ongoingprojects',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
