# Generated by Django 2.0.4 on 2018-11-15 16:13

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('projects', '0005_auto_20181112_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectimage1',
            new_name='projectimages',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectimage2',
            new_name='requirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectimage3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirement1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirement2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirement3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirement4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirement5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='concept',
        ),
        migrations.AddField(
            model_name='project',
            name='concept',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
