# Generated by Django 2.0.4 on 2018-11-15 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0006_auto_20181115_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='concept',
            new_name='concepts',
        ),
    ]
