# Generated by Django 2.0.4 on 2018-11-15 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_auto_20181115_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectimages',
            new_name='project_images',
        ),
    ]
