# Generated by Django 2.0.4 on 2018-11-15 16:39

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0009_auto_20181115_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='concepts',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
