# Generated by Django 2.0.4 on 2018-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0011_auto_20181115_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
