# Generated by Django 2.0.4 on 2018-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0012_auto_20181115_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='slug',
            field=models.SlugField(default='web', editable=False),
            preserve_default=False,
        ),
    ]
