# Generated by Django 2.0.4 on 2018-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0014_auto_20181115_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
