# Generated by Django 2.0.4 on 2018-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0016_auto_20181115_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
