# Generated by Django 2.0.4 on 2018-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0017_devtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
