# Generated by Django 2.0.4 on 2018-11-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0018_auto_20181115_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
