# Generated by Django 2.0.4 on 2018-11-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0019_auto_20181115_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='devtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='projects.DevType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='projects.Framework'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projecttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='projects.ProjectType'),
        ),
    ]
