# Generated by Django 2.0.4 on 2018-11-15 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_auto_20181115_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=False, to='projects.Framework')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=False, to='projects.Language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('recruiter',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ongoingprojects',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='ongoingprojects',
            name='language',
        ),
    ]
