# Generated by Django 2.0.4 on 2018-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stage',
            field=models.CharField(choices=[('profile_type_selection', 'profile_type_selection'),
                                            ('recruiter_filling_details', 'recruiter_filling_details'),
                                            ('developer_filling_details', 'developer_filling_details'),
                                            ('complete', 'complete')], default='profile_type_selection',
                                   max_length=100),
        ),
    ]
