# Generated by Django 2.0.4 on 2018-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20181115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
