# Generated by Django 2.0.4 on 2018-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20181115_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stage',
            field=models.CharField(choices=[('recruiter_filling_details', 'recruiter_filling_details'),
                                            ('developer_filling_details', 'developer_filling_details'),
                                            ('complete', 'complete')], default='developer_filling_details',
                                   max_length=100),
        ),
    ]
