# Generated by Django 2.0.4 on 2018-11-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodelnInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.NullBooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
