# Generated by Django 2.0.4 on 2018-11-13 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_codelninvitation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodelnInvitation',
            new_name='TestInvitation',
        ),
    ]
