# Generated by Django 2.0.4 on 2018-11-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0023_auto_20181115_1831'),
        ('transactions', '0003_auto_20181113_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recruiter_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.RecruiterProject'),
        ),
    ]
