# Generated by Django 2.0.4 on 2018-11-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0023_auto_20181115_1831'),
        ('transactions', '0004_auto_20181115_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitation',
            name='recruiter_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.RecruiterProject'),
        ),
    ]
